### ISSUE TITLE
AppImage does not run on Xubuntu 18.04

### ISSUE THREAD

**Issue by probonopd** [konradmb/zegarek#1]
```
could not load: libgdk-3.so.0

compile with -d:nimDebugDlOpen for more information
```

It needs to be bundled inside the AppImage.
How did you produce the AppImage?

Reference:
https://github.com/AppImage/appimage.github.io/pull/1991

**Comment by konradmb** [comment]
Well, that's weird, because it is bundled.  I've checked now with `--appimage-mount` and it is there.

> How did you produce the AppImage?

As I couldn't find automatic builder for GTK 3, like for QT, I've done it manually.

I create AppDir inside Docker, copy all required libs and build it with linuxdeploy. 
The list of libs is inside `Dockerfile`.
You can execute `nimble appimageDocker` to check it out.

**Comment by konradmb** [comment]
Compiled it with `-d:nimDebugDlOpen`:
```shell
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_ZegareGWFtIV/usr/bin/../lib/libcairo.so.2)
could not load: libgdk-3.so.0
```

So I need to compile it on old CentOS then…

**Comment by probonopd** [comment]
> As I couldn't find automatic builder for GTK 3, like for QT, I've done it manually.

You might be interested in trying the still-experimental https://github.com/probonopd/go-appimage/tree/master/src/appimagetool - it can do this sort of thing; be sure to let me know if you are running into any issues as this is still very new. Thanks :+1:

**Comment by konradmb** [comment]
Ok, now I'm building it in CentOS.
@probonopd Can you test it out? It runs for me in Xubuntu 18.10.

I'll checkout the new appimagetool later. Does it recognize runtime-loaded libs, i.e. those that aren't 
listed with `ldd`?

**Comment by probonopd** [comment]
> Does it recognize runtime-loaded libs

You mean with `dlopen()`? No, it doesn't recognize those at the moment, but you can copy them in manually.

**Comment by probonopd** [comment]
What is your reason for using `dlopen()`?

**Comment by konradmb** [comment]
The library that exposes GTK in Nim (https://github.com/StefanSalewski/gintro) does it that way.

**Comment by konradmb** [comment]
Confirmed solved with https://github.com/AppImage/appimage.github.io/pull/2027
